name: flutter_todo_app
description: "2023 MADC(Mobile App Developer Conference) Flutter Todo App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

